#!/usr/bin/env python

import os, sys, socket

fcontent = '''
[Ask]
Message=Btrfs Backups Key
PID=%d
Echo=0
Socket=/run/btrfs-backup/ask
NotAfter=0
''' % os.getpid()

sock = '/run/btrfs-backup/ask'

s = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
s.bind(sock)

fo = open('/run/systemd/ask-password/ask.btrfs-backup', 'w')
for l in fcontent:
    fo.write(l)
fo.close()

resp = s.recv(1024)
s.close()
os.unlink('/run/btrfs-backup/ask')
os.unlink('/run/systemd/ask-password/ask.btrfs-backup')

if resp[0] == '-':
    sys.stderr.write('Failed to read in btrfs-backup password')
    raise SystemExit(1)

sys.stdout.write(resp[1:])
