#!/bin/ksh

if [[ $(id -u) != 0 ]]; then
    sudo "$0" "$@"
    exit $?
fi

. ~+/config
_uuid="${!CONF[backups][@]}"

mount -o subvolid=0 UUID="${CONF[backups][$_uuid][localuuid]}" "${CONF[dirs][self]}"

#umount "${CONF[dirs][self]}"
