#!/bin/ksh -x


SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"

encrypted="true"
_uuid="${!CONF[backups][@]}"
_user="root"
_host="hildegarde.baburke.net"
_path="/export/share/backups"
_loop=$(losetup -f)

export SSH_AUTH_SOCK

echo "Adding remote"
sshfs "${_user}@${_host}:${_path}" "${CONF[dirs][remote]}"

losetup "$_loop" "${CONF[dirs][remote]}/klaus.img"

if "$encrypted"; then
    _tmpdir="$(mktemp -d /dev/shm/btrfs-backups.XXXXXXXXXX)"
    _luksuuid="$(cryptsetup luksUUID $_loop)"
    sudo "${!CONF[dbusenv][@]}"="${CONF[dbusenv][@]}" -u ${CONF[adminuser]} secret-tool lookup tool btrfs-backups > "$_tmpdir/.f"
    cryptsetup open "$_loop" "luks-$_luksuuid" --key-file "$_tmpdir/.f"
    rm -rf "$_tmpdir"
fi

mount -o compress,subvolid=0 "/dev/mapper/luks-$_luksuuid" "${CONF[dirs][backups]}"

#df -h
#sleep 10
#echo "Removing remote"

#umount "${CONF[dirs][backups]}"
#cryptsetup close "$_mappername"
#losetup -d "$_loop"
#fusermount -u "${CONF[dirs][remote]}"

#df -h
