#!/bin/ksh

set -e
set -o braceexpand

typeset -A _devices
typeset _date=$(date +"%F-%H")
typeset _config=~+/config

# Flags
qflag="false"

while getopts ':q' _opt; do
    case "$_opt" in
        "q")
            qflag="true"
        ;;
        "?")
            echo "Bad argument -$_opt" 1>&2
            # usage
            exit 1
    esac
done

_msg()
{
    $qflag || echo "$@"
}

. "$_config"

# Subvolumes on device, relative to btrfs root
for _uuid in "${!CONF[backups][@]}"; do
    typeset -n _conf="CONF[backups][$_uuid]"

    _msg "+ Processing backup id $_uuid"
    mount -o subvolid=0 UUID="${_conf[localuuid]}" "${CONF[dirs][self]}"

    for _v in "${_conf[volumes][@]}"; do
        _p="${CONF[dirs][self]}/$_v"

        _msg "+ Snapshotting subvolume $_v at $_date"
        btrfs subvolume snapshot -r "$_p" "$_p-$_date" >/dev/null 2>&1
    done

    umount "${CONF[dirs][self]}"
done

_msg "+ Exiting"
